// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW_jpvM1DHFUMhJOQE0pP_FjF3pLJUaPg',
    appId: '1:241251279248:web:862b3ad193a5ff93589315',
    messagingSenderId: '241251279248',
    projectId: 'automation-1a6c6',
    authDomain: 'automation-1a6c6.firebaseapp.com',
    databaseURL: 'https://automation-1a6c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'automation-1a6c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQLDyQGbFmE5Y2Nuu0_8kr3cZ8hfx49VU',
    appId: '1:241251279248:android:e6ff9fbddbf5db51589315',
    messagingSenderId: '241251279248',
    projectId: 'automation-1a6c6',
    databaseURL: 'https://automation-1a6c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'automation-1a6c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB2KK9RITucqnhvK4BofTAYRTkc5ngjcQ',
    appId: '1:241251279248:ios:f2038e308937a66f589315',
    messagingSenderId: '241251279248',
    projectId: 'automation-1a6c6',
    databaseURL: 'https://automation-1a6c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'automation-1a6c6.firebasestorage.app',
    iosBundleId: 'com.example.automation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB2KK9RITucqnhvK4BofTAYRTkc5ngjcQ',
    appId: '1:241251279248:ios:f2038e308937a66f589315',
    messagingSenderId: '241251279248',
    projectId: 'automation-1a6c6',
    databaseURL: 'https://automation-1a6c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'automation-1a6c6.firebasestorage.app',
    iosBundleId: 'com.example.automation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW_jpvM1DHFUMhJOQE0pP_FjF3pLJUaPg',
    appId: '1:241251279248:web:baa3a80af64f01fc589315',
    messagingSenderId: '241251279248',
    projectId: 'automation-1a6c6',
    authDomain: 'automation-1a6c6.firebaseapp.com',
    databaseURL: 'https://automation-1a6c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'automation-1a6c6.firebasestorage.app',
  );
}
